[color]
server_online_race = "#3eb3f7"
server_online_battle = "#f7283c"
server_online_custom = "#42ed53"
server_offline = "#1b1b27"

[messages]
gathered = [
  "A dark, forboding feeling overtakes you. You know this Mogi's conclusion, even in its infancy.",
  "<@&1336926299221917778> why you trying not to laugh",
  "<:zazakiller:1437184417540997241>",
  "<:trolley:1384661421358317735>",
  "Night 6",
  "oh no bro",
  "backing quads tight gl",
  "Do you know who else canned up for a mogi in the Dr. Robotnik's Ring Racers Lounge?",
  "\"Daniel please stop canning\"",
  "Mario has logged in.",
  "time to farm!",
  "we might be cooked.",
  "the plan is simple",
  "the plan is rather complex in nature",
  "so two bronzes walked into tier wall",
  "why are they moving",
  "50 pons to gutbuster",
  "Gutbuster has sent deathlink",
  "it's so chill",
  "I believe <@230853305234882560> is going to enjoy this ðŸ‘€",
  "gah damn",
  "who wants to can for 2.3 derby?",
  "\"can down\" - gunla 2025",
  "guess what",
  "chicken butt",
]
